### ISSUE TITLE
TITAN2D installation issues

### ISSUE THREAD

**Issue by seljr257** [TITAN2D/titan2d#3]
As I was about to compile it using 
``make -j``
this error shows up:

> ../../../../titan2d/src/geoflow/stats.C: In member function ‘void StatProps::calc_stats(int, MatProps*, TimeProps*, DischargePlanes*, LocalQuants*, double)’:
../../../../titan2d/src/geoflow/stats.C:172:22: error: ‘HUGE’ was not declared in this scope
     double m_x_min = HUGE;
                      ^~~~
Makefile:382: recipe for target 'stats.o' failed
make[2]: *** [stats.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/flux_srcs.Tpo .deps/flux_srcs.Po
mv -f .deps/integrators.Tpo .deps/integrators.Po
make[2]: Leaving directory '/home/lnp/titan_wsp/titan2d_bld/iccoptompmpi/src/geoflow'
Makefile:356: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lnp/titan_wsp/titan2d_bld/iccoptompmpi/src'
Makefile:382: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I am installing titan2d using Ubuntu 18.04 LTS on Windows 10. I am cloning titan2d using github.

**Comment by nsimakov** [comment]
Hello,
Thanks for bug report. I think I saw such problem earlier and thought we fixed it. Basically it is either newer compilers/libraries don't use HUGE macro anymore or we didn't include proper header. Let me take a look into it.
-Nikolay

**Comment by nsimakov** [comment]
Fixed at 9ab90d4370b9ac7b6bbc926d693718660b0d202f. HUGE macro from math.h is hidden on ubuntu replaced it with HUGE_VAL.
-Nikolay
